spring:
  datasource:
    url: jdbc:mysql://localhost:3306/neuropsi?reconnect=true&useSSL=false&serverTimezone=UTC
    username: vemm
    password: abc123??
    initialization-mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect