spring:
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_df2033176d61b3d?reconnect=true
    username: b65e4109baf036
    password: 1428af9d
    initialization-mode: NEVER
    tomcat:
      initial-size: 2
      max-wait: 20000
      max-active: 3
      max-idle: 3
      min-idle: 2
      default-auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true
