logging:
  level:
    org:
      springframework:
        web: debug
server:
  port: ${PORT:9090}
  servlet:
    context-path: /api/record
spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: neuropsi-record-service
  profiles:
    active: ${PROFILE:dev}
  security:
    user:
      name: ${USERNAME:username}
      password: ${PASSWORD:password}
    oauth:
      clientId: vueNeuropsi
      clientSecret: 6a26c09683332161f2654a271e321ea8
      accessTokenValiditySeconds: 9600
      refreshTokenValiditySeconds: 9600
      scopes: read,write
      grantTypes: password,refresh_token
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: neuropsi.escom@gmail.com
    password: abc123??
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
eureka:
  instance:
    hostname: ${HOSTNAME:localhost}
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://username:password@localhost:8761}/eureka/
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
auth:
  server:
    #host: https://arcane-depths-42325.herokuapp.com
    host: ${OAUTH_URL:localhost:8762/auth}