logging:
  level:
    org:
      springframework:
        web: debug
server:
  port: ${SERVER_POR:8090}
  servlet:
    context-path: /api/record
spring:
  application:
    name: neuropsi-record-service
  profiles:
    active: ${PROFILE:prod}
  security:
    user:
      name: ${USERNAME:username}
      password: ${PASSWORD:password}
    oauth:
      clientId: vueNeuropsi
      clientSecret: 6a26c09683332161f2654a271e321ea8
      accessTokenValiditySeconds: 9600
      refreshTokenValiditySeconds: 9600
      scopes: read,write
      grantTypes: password,refresh_token
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:https://neuropsi:0e4e034f3504195e386b1bdcf4fbfe78@safe-shore-20278.herokuapp.com}/eureka/
      #defaultZone: ${EUREKA_URL:http://username:password@localhost:8761}/eureka/
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
auth:
  server:
    # http://protected-caverns-83632.herokuapp.com
    host: ${AUTH_URL:localhost:8090}/auth